### PR TITLE
Adding a modulesFolder option to allow overriding the directory to check...

### PR DESCRIPTION
**Pull request by herbrandson**
... for dependencies (previously hardcoded to node_modules)

### CODE REVIEW

**Comment by othiym23** [comment]
What's the use case for this change? I know it seems pretty self-contained (although it would need a test to land), but `read-installed`, due to its reliance on `read-package-json` and `readdir-scoped-modules`, is pretty much optimized solely for use with npm. I'd really like to avoid adding configurability that moves away from that without strong motivation.

**Comment by herbrandson** [comment]
I'm working on a utility to check the package.json against node_modules to see which packages are missing and/or wrong versions. With this small change to read-installed I would be able to use the same code to also check bower.json against bower_components.

This utility will be used as part of a gulp/grunt "watch" task. The idea is that when a developer pulls in new changes from git, this dependency-checker task will run and immediately let them know if they need to do an npm/bower install.

**Comment by othiym23** [comment]
In that case, I don't think this change makes sense, and am -1 on it. As I said previously, there's a lot of magic baked in to `read-package-json` and some of the other dependencies of `read-installed` specifically for dealing with npm stuff. It might work for your purposes for Bower, and it might not, but I think you're way better off writing a purpose-built checker that's optimized for Bower.

**Comment by herbrandson** [comment]
I was afraid you'd say that ;). I was hoping that removing the hardcoded reference to "node_modules" would be motivation enough. It does look like `read-package-json` also has one hardcoded reference to "node_modules" (line #129). I could remove that one as well if it would help my case.

**Comment by othiym23** [comment]
I don't want to rule out npm relaxing its dependencies on `node_modules` in the future, as we're still considering our options for making npm work better for managing front-end dependencies, but that should be done in the context of an overall change to npm, not just ad hoc like this.

> It does look like `read-package-json` also has one hardcoded reference to "node_modules" (line #129). I could remove that one as well if it would help my case.

I think that just goes to underline my point – these modules aren't general-purpose filesystem tree-walkers that just happen to know about semver, they're calling things like `normalize-package-data` and `readdir-scoped-modules` that have lots of domain-specific specialization for npm. Repackaging them for other purposes might work now, but we've made pretty drastic changes to them recently for npm-related reasons, and pretty much have to reserve the right to do so in the future, so depending on their current behavior to work for a different package manager (which Bower is) seems like a bad plan to me.

**Comment by herbrandson** [comment]
Ok, fair enough. I get where you're coming from and I can't say as I 100% disagree w/ you.

**Comment by iarna** [comment]
It seems like this settled on a decision not to take this pull request, so I'm going to close this. Drop a note here if that's not the case and I'll reopen it.

**Pull request closed without merging**
