### PR TITLE
better peerinvalid error info

### PR DESCRIPTION
**Pull request by amir-arad**
(Also, CI now tests correctly and all tests pass)

I'm tracking down a bug that has the same root cause as npm/npm#10538 and npm/npm#10635 . 
It seems that npm install is looking for the peerinvalid flag in the result, and then attempts to guess the cause by shallow-scanning the dependency in the same level as the one marked peerinvalid.

This is a prerequisite for my suggestion of a fix: let read-installed supply a concrete conflict information, so that npm can use it to construct the correct error message.

### CODE REVIEW

**Comment by zkat** [comment]
Hey! I'm not entirely sure what role this package has at this point in the larger scope of things, but I'm sure I can cc @iarna for more details/discussion of this. It might still be a while before we get to this, though. Thanks for the time taken with this. :)

**Comment by amir-arad** [comment]
@zkat was glad to do it

even if it's discarded, please consider fixing CI for future contributors, see  commit 2c5c4bae217d92da6df9d236f7a574f09a7f27f4

**Comment by iarna** [comment]
This module is, of course, still used by npm's lts release. npm@3, by contrast, only has one or two remaining places that use it. It's been replaced by a combination of `read-package-tree` and the internals of npm@3. In so far as there are bugs in this module, that generally means bugs in npm lts, which we are  AFAIK still taking bug fixes to (@zkat?)

@amir-arad If you could split your PR up to separate the gitignore & testing changes from your code changes that would be much appreciated!

**Comment by iarna** [comment]
I've looked over the changes and I don't see any reason we couldn't take this? I would expect this would need to be paired with a PR against [npm/npm#lts](https://github.com/npm/npm/tree/lts) to take advantage of these changes, but merging this here first makes sense to me.

**Comment by amir-arad** [comment]
@iarna that was my intention all along

**Comment by amir-arad** [comment]
Anyone?

**Comment by amir-arad** [comment]
hello?

**Comment by amir-arad** [comment]
dum dum dum...

**Comment by amir-arad** [comment]
well they did say NPM  is slow but I didn't think it was *that* slow

**Comment by mightyiam** [comment]
Keep it open, if it's still relevant, please.

**Comment by amir-arad** [comment]
@mightyiam 
I'm curating my PRs (and forks) from time to time. feel free to fork amir-arad/read-installed/patch-1 and open a PR if you wish.

**Pull request closed without merging**
